{
 "title": "NodeJS Application Dashboard",
 "description": "node.js prometheus client basic metrics",
 "tags": [ "nodejs" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "db_instance",
    "label": "DB_Instance",
    "query": {
     "query": "query_result(pg_up{release=\"$release\"})"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(nodejs_version_info, instance)"
    }
   },
   {
    "name": "release",
    "label": "Release",
    "query": {
     "query": "query_result(pg_exporter_last_scrape_duration_seconds{kubernetes_namespace=\"$namespace\"})"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "query_result(pg_exporter_last_scrape_duration_seconds)"
    }
   },
   { "name": "datname", "label": "Database", "query": { "query": "label_values(datname)" } },
   {
    "name": "mode",
    "label": "Lock table",
    "query": {
     "query": "label_values({mode=~\"accessexclusivelock|accesssharelock|exclusivelock|rowexclusivelock|rowsharelock|sharelock|sharerowexclusivelock|shareupdateexclusivelock\"}, mode)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Database stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{release=\"$release\", instance=\"$db_instance\"}[5m]) * 1000)",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "graph",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{release=\"$release\", instance=\"$db_instance\"}[5m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{release=\"$release\", instance=\"$db_instance\"}[5m]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Update data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_updated{datname=~\"$datname\", instance=~\"$db_instance\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Fetch data (SELECT)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_fetched{datname=~\"$datname\", instance=~\"$db_instance\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Delete data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_deleted{datname=~\"$datname\", instance=~\"$db_instance\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Insert data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_inserted{datname=~\"$datname\", instance=~\"$db_instance\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  { "title": "Kuber metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "MEMORY pod usage (mb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{container=\"crud-user-chart\"}[5m]) / 1024 / 1024) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU pod usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"crud-user-chart\"}[5m])) by (name) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Nginx requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Latency by le",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n      sum by (le, path) \n         (rate(nginx_ingress_controller_request_duration_seconds_bucket{path=\"/app/(.*)\"}[1m]))\n) * 1000",
     "legendFormat": "0.5 le"
    },
    {
     "expr": "histogram_quantile(0.95, \n      sum by (le, path) \n         (rate(nginx_ingress_controller_request_duration_seconds_bucket{path=\"/app/(.*)\"}[1m]))\n) * 1000",
     "legendFormat": "0.95 le"
    },
    {
     "expr": "histogram_quantile(0.99, \n      sum by (le, path) \n         (rate(nginx_ingress_controller_request_duration_seconds_bucket{path=\"/app/(.*)\"}[1m]))\n) * 1000",
     "legendFormat": "0.99 le"
    },
    {
     "expr": "histogram_quantile(1, \n      sum by (le, path) \n         (rate(nginx_ingress_controller_request_duration_seconds_bucket{path=\"/app/(.*)\"}[1m]))\n) * 1000",
     "legendFormat": "max le {{method}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "sum by (route) (rate(nginx_ingress_controller_request_duration_seconds_count{path=\"/app/(.*)\"}[1m]))",
     "legendFormat": "RPS{{route}}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"^[4-5]..$\"}[1m]))"
    }
   ]
  },
  { "title": "App requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Latency by le",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n      sum by (le) \n         (rate(http_request_duration_seconds_bucket{route=~\"^/api/user.*\"}[1m]))\n) * 1000",
     "legendFormat": "0.5 le"
    },
    {
     "expr": "histogram_quantile(0.95, \n      sum by (le) \n         (rate(http_request_duration_seconds_bucket{route=~\"^/api/user.*\"}[1m]))\n) * 1000",
     "legendFormat": "0.95 le"
    },
    {
     "expr": "histogram_quantile(0.99, \n      sum by (le) \n         (rate(http_request_duration_seconds_bucket{route=~\"^/api/user.*\"}[1m]))\n) * 1000",
     "legendFormat": "0.99 le"
    },
    {
     "expr": "histogram_quantile(1, \n      sum by (le) \n         (rate(http_request_duration_seconds_bucket{route=~\"^/api/user.*\"}[1m]))\n) * 1000",
     "legendFormat": "max le {{pod}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "targets": [
    {
     "expr": "sum(rate(http_request_summary_seconds_count{route=~\"^/api/user.*\"}[1m]))",
     "legendFormat": "RPS{{route}}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status_code=~\"^[4-5]..$\"}[1m]))"
    }
   ]
  }
 ]
}