apiVersion: apps/v1
kind: Deployment
metadata:
    name: base-deployment
spec:
    replicas: 2
    selector:
       matchLabels:
          app: base-app
    template:
       metadata:
          labels:
             app: base-app
       spec:
          containers:
          - name: base-app-container
            image: aircrisp/otus-app:homework1
            ports:
              - name: web
                containerPort: 8080
            readinessProbe:
              httpGet:
                port: 8080
                path: /health
              initialDelaySeconds: 10
              periodSeconds: 5
