apiVersion: batch/v1
kind: Job
metadata:
  name: user-down-migration
spec:
  template:
    spec:
      containers:
      - name: postgres
        env:
          - name: DATABASE_URI
            value: "postgresql://myuser:passwd@postgres:5432/crudapp"
        image: postgres:latest
        command:
          - sh
          - "-c"
          - |
            psql $DATABASE_URI <<'EOF'
              drop table "aircrisp_user";
            EOF
      restartPolicy: Never
  backoffLimit: 4